version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: always
        volumes:
            - ./:/var/www
            - ./storage:/var/www/storage
        environment:
            - "DB_HOST=db"
            - "DB_PORT=3306"
        depends_on:
            - db

    db:
        image: mysql:5.7.31
        container_name: laravel_db
        restart: always
        environment:
            MYSQL_DATABASE: ucc
            MYSQL_USER: root
            MYSQL_PASSWORD: tupassword
            MYSQL_ROOT_PASSWORD: tupassword
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    webserver:
        image: nginx:alpine
        container_name: laravel_nginx
        restart: always
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

volumes:
    mysql_data:
